# Generated by Django 2.1.7 on 2019-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureaccessories',
            name='option',
            field=models.CharField(choices=[('Blum', 'BlUM'), ('Hettich', 'HETTICH')], default='11', max_length=30, verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
