# Generated by Django 2.1.7 on 2019-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_furnitureaccessories_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafs',
            name='option',
            field=models.CharField(choices=[('photoprint', 'Фотопечать'), ('decorated', 'Декоративные перегородки'), ('sandblast', 'Пескоструи'), ('ekokozha', 'Экокожа'), ('laminirovanie', 'Ламинирование ДСП')], default='sandblast', max_length=100, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
