# Generated by Django 2.1.5 on 2019-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30, verbose_name='Заказчик')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новая заказ'), ('in_process', 'Заказ в процессе обработки'), ('renouncement', 'Заказ отклонен'), ('complete', 'Заказ выполнен '), ('?', 'Не получен ответ пользователя')], default='new', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
