# Generated by Django 2.1.5 on 2019-02-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.CharField(default=0, max_length=30, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
