# Generated by Django 2.1.5 on 2019-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.CharField(default=0, max_length=30, verbose_name='Стоимость'),
        ),
    ]
