# Generated by Django 2.1.7 on 2019-02-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('option', models.CharField(choices=[('kitchens', 'КУХНИ'), ('showcases', 'ВИТРИНЫ'), ('wardrobes', 'ШКАФЫ-КУПЕ'), ('offices', 'МЕБЕЛЬ ДЛЯ ОФИСА'), ('hallways', 'ПРИХОЖИЕ'), ('lounges', 'ГОСТИНЫЕ'), ('child', 'ДЕТСКИЕ'), ('closets', 'ГАРДЕРОБНЫЕ'), ('others', 'КРОВАТИ КОМОДЫ ТУМБЫ')], max_length=20)),
            ],
        ),
    ]
